project:
  type: book
  output-dir: Renders
lang: es
book:
  title: "Memoria"
  author: "Blanca Cano Camarero y Iker Villegas Labairu."
  date: \today
  chapters:
    - index.qmd
    - intro.qmd
    - 04_calculo_spikes.qmd
    - 05_calculo_informacion_mutua.qmd
    - 06_entropia_normalizada.qmd
    - 07_SAX.qmd
    - summary.qmd
    - references.qmd
    - appendix.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt





